import { FormEvent, useState, type ReactNode } from 'react'
import { useSearchParams } from 'react-router-dom'
import { ApiClientError } from '../../api/client'
import type { User, UserRole } from '../../auth/types'
import { useAuth } from '../../auth/authContext'
import { getAdminActionMessage, getSettingInputType, roleRequiresBranch } from './adminUtils'
import { useAdminMutations, useBranches, useSettings, useUsers } from './adminApi'
import type { Branch, BranchPayload, Setting, UserPayload } from './types'
import { ConfirmationDialog, EmptyState, Pagination, StatusBadge } from '../../components/AdminUI'

function errorMessage(error: unknown): string { return error instanceof ApiClientError ? error.message : error instanceof Error ? error.message : 'The request could not be completed.' }
function fieldError(error: unknown, field: string): string | undefined { const details = error instanceof ApiClientError ? error.details : undefined; const value = details?.[field]; return typeof value === 'string' ? value : Array.isArray(value) ? String(value[0]) : undefined }
function useListState() { const [params, setParams] = useSearchParams(); const page = Number(params.get('page') || '1'); const perPage = params.get('per_page') || '20'; const search = params.get('search') || ''; const set = (values: Record<string, string | number | undefined>) => { const next = new URLSearchParams(params); Object.entries(values).forEach(([key, value]) => value === undefined || value === '' ? next.delete(key) : next.set(key, String(value))); setParams(next) }; return { params, page, perPage, search, set } }

export function UsersPage() {
  const list = useListState(); const query = useUsers({ search: list.search, page: String(list.page), per_page: list.perPage }); const mutations = useAdminMutations(); const [editing, setEditing] = useState<User | null>(null); const [creating, setCreating] = useState(false); const [confirm, setConfirm] = useState<User | null>(null)
  const rows = query.data?.rows || []
  return <div className="admin-page"><AdminHeader eyebrow="Administration" title="Users" description="Manage account access and active status." action={<button onClick={() => setCreating(true)}>Create user</button>} /><div className="admin-toolbar"><input aria-label="Search users" placeholder="Search by name or email" value={list.search} onChange={(event) => list.set({ search: event.target.value, page: 1 })} /><button className="secondary-button" onClick={() => void query.refetch()}>Refresh</button></div>{query.isPending ? <LoadingRows /> : query.isError ? <div className="inline-error" role="alert"><strong>Unable to load users</strong><span>{errorMessage(query.error)}</span></div> : rows.length === 0 ? <EmptyState title="No users found">Try a different search or create the first account.</EmptyState> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Branch</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((user) => <tr key={user.id}><td><strong>{user.full_name}</strong></td><td>{user.email}</td><td>{user.role.replaceAll('_', ' ')}</td><td>{user.branch_id || 'Head office'}</td><td><StatusBadge active={user.is_active} /></td><td><div className="table-actions"><button className="table-button" onClick={() => setEditing(user)}>Edit</button><button className="table-button" onClick={() => setConfirm(user)}>{user.is_active ? 'Deactivate' : 'Activate'}</button></div></td></tr>)}</tbody></table></div>}<Pagination page={list.page} pages={query.data?.meta?.pages || 1} onPage={(page) => list.set({ page })} />{(creating || editing) && <UserForm user={editing} pending={mutations.createUser.isPending || mutations.updateUser.isPending} error={mutations.createUser.error || mutations.updateUser.error} onCancel={() => { setCreating(false); setEditing(null) }} onSubmit={async (payload) => { if (editing) await mutations.updateUser.mutateAsync({ id: editing.id, payload }); else await mutations.createUser.mutateAsync(payload); setCreating(false); setEditing(null) }} />}{confirm && <ConfirmationDialog open title={`${confirm.is_active ? 'Deactivate' : 'Activate'} ${confirm.full_name}?`} message={getAdminActionMessage('user', confirm.is_active)} pending={mutations.setUserStatus.isPending} onCancel={() => setConfirm(null)} onConfirm={async () => { await mutations.setUserStatus.mutateAsync({ id: confirm.id, is_active: !confirm.is_active }); setConfirm(null) }} />}</div>
}

function UserForm({ user, pending, error, onCancel, onSubmit }: { user: User | null; pending: boolean; error: unknown; onCancel: () => void; onSubmit: (payload: UserPayload) => Promise<void> }) {
  const [form, setForm] = useState<UserPayload>({ full_name: user?.full_name || '', email: user?.email || '', password: '', role: user?.role || 'SALES_REP', branch_id: user?.branch_id || '', phone: user?.phone || '', is_active: user?.is_active ?? true }); const set = (key: keyof UserPayload, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }))
  async function submit(event: FormEvent) { event.preventDefault(); await onSubmit({ ...form, password: form.password || undefined, branch_id: form.branch_id || undefined }) }
  return <Modal title={user ? 'Edit user' : 'Create user'} onClose={onCancel}><form className="admin-form" onSubmit={submit}><FormInput label="Full name" value={form.full_name} onChange={(value) => set('full_name', value)} error={fieldError(error, 'full_name')} required /><FormInput label="Email" type="email" value={form.email} onChange={(value) => set('email', value)} error={fieldError(error, 'email')} required /><label>Role<select value={form.role} onChange={(event) => set('role', event.target.value as UserRole)}>{(['ADMIN', 'HO_STAFF', 'BRANCH_MANAGER', 'SALES_REP', 'ACCOUNTS'] as UserRole[]).map((role) => <option key={role}>{role}</option>)}</select></label><FormInput label={user ? 'New password (optional)' : 'Password'} type="password" value={form.password || ''} onChange={(value) => set('password', value)} error={fieldError(error, 'password')} required={!user} /><FormInput label={roleRequiresBranch(form.role) ? 'Branch ID' : 'Branch ID (optional)'} value={form.branch_id || ''} onChange={(value) => set('branch_id', value)} error={fieldError(error, 'branch_id')} required={roleRequiresBranch(form.role)} /><FormInput label="Phone (optional)" value={form.phone || ''} onChange={(value) => set('phone', value)} /><div className="modal-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancel</button><button disabled={pending}>{pending ? 'Saving...' : 'Save user'}</button></div>{Boolean(error) && <div className="form-message error" role="alert">{errorMessage(error)}</div>}</form></Modal>
}

export function BranchesPage() {
  const auth = useAuth(); const list = useListState(); const query = useBranches({ search: list.search, page: String(list.page), per_page: list.perPage }); const mutations = useAdminMutations(); const [editing, setEditing] = useState<Branch | null>(null); const [creating, setCreating] = useState(false); const [confirm, setConfirm] = useState<Branch | null>(null); const admin = auth.user?.role === 'ADMIN'; const rows = query.data?.rows || []
  return <div className="admin-page"><AdminHeader eyebrow="Organization" title="Branches" description={admin ? 'Create and maintain branch records.' : 'View branch records available to your account.'} action={admin ? <button onClick={() => setCreating(true)}>Create branch</button> : undefined} /><div className="admin-toolbar"><input aria-label="Search branches" placeholder="Search by code or name" value={list.search} onChange={(event) => list.set({ search: event.target.value, page: 1 })} /><button className="secondary-button" onClick={() => void query.refetch()}>Refresh</button></div>{query.isPending ? <LoadingRows /> : query.isError ? <div className="inline-error" role="alert"><strong>Unable to load branches</strong><span>{errorMessage(query.error)}</span></div> : rows.length === 0 ? <EmptyState title="No branches found">Try a different search.</EmptyState> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Code</th><th>Name</th><th>Address</th><th>Warehouse</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((branch) => <tr key={branch.id}><td><strong>{branch.code}</strong></td><td>{branch.name}</td><td>{branch.address || '—'}</td><td>{branch.is_warehouse ? 'Yes' : 'No'}</td><td><StatusBadge active={branch.is_active} /></td><td>{admin ? <div className="table-actions"><button className="table-button" onClick={() => setEditing(branch)}>Edit</button>{branch.is_active && <button className="table-button" onClick={() => setConfirm(branch)}>Deactivate</button>}</div> : <span className="muted-label">Read only</span>}</td></tr>)}</tbody></table></div>}<Pagination page={list.page} pages={query.data?.meta?.pages || 1} onPage={(page) => list.set({ page })} />{admin && (creating || editing) && <BranchForm branch={editing} pending={mutations.createBranch.isPending || mutations.updateBranch.isPending} error={mutations.createBranch.error || mutations.updateBranch.error} onCancel={() => { setCreating(false); setEditing(null) }} onSubmit={async (payload) => { if (editing) await mutations.updateBranch.mutateAsync({ id: editing.id, payload }); else await mutations.createBranch.mutateAsync(payload); setCreating(false); setEditing(null) }} />}{admin && confirm && <ConfirmationDialog open title={`Deactivate ${confirm.name}?`} message={getAdminActionMessage('branch', true)} pending={mutations.deactivateBranch.isPending} onCancel={() => setConfirm(null)} onConfirm={async () => { await mutations.deactivateBranch.mutateAsync(confirm.id); setConfirm(null) }} />}</div>
}

function BranchForm({ branch, pending, error, onCancel, onSubmit }: { branch: Branch | null; pending: boolean; error: unknown; onCancel: () => void; onSubmit: (payload: BranchPayload) => Promise<void> }) { const [form, setForm] = useState<BranchPayload>({ code: branch?.code || '', name: branch?.name || '', address: branch?.address || '', manager_id: branch?.manager_id || '', is_warehouse: branch?.is_warehouse || false, invoice_prefix: branch?.invoice_prefix || '', is_active: branch?.is_active ?? true }); const set = (key: keyof BranchPayload, value: string | boolean) => setForm((current) => ({ ...current, [key]: value })); async function submit(event: FormEvent) { event.preventDefault(); await onSubmit(form) } return <Modal title={branch ? 'Edit branch' : 'Create branch'} onClose={onCancel}><form className="admin-form" onSubmit={submit}><FormInput label="Code" value={form.code} onChange={(value) => set('code', value)} error={fieldError(error, 'code')} required /><FormInput label="Name" value={form.name} onChange={(value) => set('name', value)} error={fieldError(error, 'name')} required /><FormInput label="Address" value={form.address || ''} onChange={(value) => set('address', value)} /><FormInput label="Manager ID (optional)" value={form.manager_id || ''} onChange={(value) => set('manager_id', value)} /><FormInput label="Invoice prefix" value={form.invoice_prefix || ''} onChange={(value) => set('invoice_prefix', value)} /><label className="check-field"><input type="checkbox" checked={Boolean(form.is_warehouse)} onChange={(event) => set('is_warehouse', event.target.checked)} /> Warehouse branch</label><div className="modal-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancel</button><button disabled={pending}>{pending ? 'Saving...' : 'Save branch'}</button></div>{Boolean(error) && <div className="form-message error" role="alert">{errorMessage(error)}</div>}</form></Modal> }

export function SettingsPage() { const query = useSettings(); const mutations = useAdminMutations(); const [selected, setSelected] = useState<Setting | null>(null); return <div className="admin-page"><AdminHeader eyebrow="Configuration" title="Settings" description="Review and update backend-managed application settings." />{query.isPending ? <LoadingRows /> : query.isError ? <div className="inline-error" role="alert"><strong>Unable to load settings</strong><span>{errorMessage(query.error)}</span></div> : !query.data?.length ? <EmptyState title="No settings returned">The backend has not configured any editable settings.</EmptyState> : <div className="settings-list">{query.data.map((setting) => <article className="setting-row" key={setting.key}><div><strong>{setting.key}</strong><span>{setting.data_type} · Updated {setting.updated_at || 'not available'}</span></div><div><code>{setting.value}</code><button className="table-button" onClick={() => setSelected(setting)}>Edit</button></div></article>)}</div>}{selected && <SettingForm setting={selected} pending={mutations.updateSetting.isPending} error={mutations.updateSetting.error} onCancel={() => setSelected(null)} onSubmit={async (value) => { await mutations.updateSetting.mutateAsync({ key: selected.key, value, data_type: selected.data_type }); setSelected(null) }} />}</div> }

function SettingForm({ setting, pending, error, onCancel, onSubmit }: { setting: Setting; pending: boolean; error: unknown; onCancel: () => void; onSubmit: (value: string) => Promise<void> }) { const [value, setValue] = useState(setting.value); const inputType = getSettingInputType(setting.data_type); return <Modal title={`Edit ${setting.key}`} onClose={onCancel}><form className="admin-form" onSubmit={(event) => { event.preventDefault(); void onSubmit(value) }}>{inputType === 'checkbox' ? <label className="check-field"><input type="checkbox" checked={value === 'true'} onChange={(event) => setValue(String(event.target.checked))} /> Enabled</label> : <FormInput label="Value" type={inputType} value={value} onChange={setValue} required />}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancel</button><button disabled={pending}>{pending ? 'Saving...' : 'Save setting'}</button></div>{Boolean(error) && <div className="form-message error" role="alert">{errorMessage(error)}</div>}</form></Modal> }

function AdminHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="page-heading admin-header"><div><span className="section-kicker">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div> }
function FormInput({ label, type = 'text', value, onChange, error, required = false }: { label: string; type?: string; value: string; onChange: (value: string) => void; error?: string; required?: boolean }) { return <label>{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} required={required} /><small className="field-error">{error || ''}</small></label> }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-heading"><h2 id="modal-title">{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}>×</button></div>{children}</section></div> }
function LoadingRows() { return <div className="loading-block" role="status">Loading records...</div> }
