import { useState, type FormEvent, type ReactNode } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ApiClientError } from '../../api/client'
import { useAuth } from '../../auth/authContext'
import { ConfirmationDialog, EmptyState, Pagination, StatusBadge } from '../../components/AdminUI'
import { formatMoney } from '../../lib/money'
import { useCustomer, useCustomers, useCustomerStatement, useExpenseCategories, usePartnerMutations, useSupplier, useSuppliers } from './partnerApi'
import { canManageExpenseCategories, canManageMasterData, deactivationMessage, statementReconciles } from './partnerUtils'
import type { Customer, CustomerPayload, ExpenseCategory, ExpenseCategoryPayload, MasterEntity, Supplier, SupplierPayload } from './types'

function message(error: unknown) { return error instanceof Error ? error.message : 'The request could not be completed.' }
function fieldError(error: unknown, field: string) { const value = error instanceof ApiClientError ? error.details?.[field] : undefined; return typeof value === 'string' ? value : Array.isArray(value) ? String(value[0]) : undefined }
type SearchSetter = (value: URLSearchParams | ((current: URLSearchParams) => URLSearchParams)) => void
function setUrl(_params: URLSearchParams, setParams: SearchSetter, key: string, value: string) { setParams((current) => { const next = new URLSearchParams(current); if (value) next.set(key, value); else next.delete(key); if (key !== 'page') next.set('page', '1'); return next }) }

export function CustomersPage() {
  const auth = useAuth(); const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const mutations = usePartnerMutations(); const [selected, setSelected] = useState<Customer | null>(null); const [creating, setCreating] = useState(false); const [confirm, setConfirm] = useState<Customer | null>(null)
  const filters = { search: params.get('search') || '', active: params.get('active') || '', page: params.get('page') || '1', per_page: '20' }; const query = useCustomers(filters); const manage = canManageMasterData(auth.user?.role)
  return <div className="admin-page partner-page"><MasterPage title="Customers" description="Manage customer identities, credit limits, and account statements." rows={query.data?.rows || []} loading={query.isPending} error={query.error} filters={filters} setFilter={(key, value) => setUrl(params, setParams, key, value)} pages={query.data?.meta?.pages || 1} entity="customer" manage={manage} onCreate={() => setCreating(true)} onEdit={(row) => setSelected(row as Customer)} onDeactivate={(row) => setConfirm(row as Customer)} />
    {(creating || selected) && <CustomerForm customer={selected} pending={mutations.createCustomer.isPending || mutations.updateCustomer.isPending} error={mutations.createCustomer.error || mutations.updateCustomer.error} onClose={() => { setCreating(false); setSelected(null) }} onSubmit={async (payload) => { if (selected) await mutations.updateCustomer.mutateAsync({ id: selected.id, payload }); else { const created = await mutations.createCustomer.mutateAsync(payload); navigate(`/customers/${created.id}`) } setCreating(false); setSelected(null) }} />}
    <ConfirmationDialog open={Boolean(confirm)} title="Deactivate customer" message={confirm ? deactivationMessage('customer', confirm.name) : ''} pending={mutations.deactivateCustomer.isPending} onCancel={() => setConfirm(null)} onConfirm={() => { if (confirm) void mutations.deactivateCustomer.mutateAsync(confirm.id).then(() => setConfirm(null)) }} />
  </div>
}

export function SuppliersPage() {
  const auth = useAuth(); const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const mutations = usePartnerMutations(); const [selected, setSelected] = useState<Supplier | null>(null); const [creating, setCreating] = useState(false); const [confirm, setConfirm] = useState<Supplier | null>(null)
  const filters = { search: params.get('search') || '', active: params.get('active') || '', page: params.get('page') || '1', per_page: '20' }; const query = useSuppliers(filters); const manage = canManageMasterData(auth.user?.role)
  return <div className="admin-page partner-page"><MasterPage title="Suppliers" description="Maintain supplier contacts and payment terms." rows={query.data?.rows || []} loading={query.isPending} error={query.error} filters={filters} setFilter={(key, value) => setUrl(params, setParams, key, value)} pages={query.data?.meta?.pages || 1} entity="supplier" manage={manage} onCreate={() => setCreating(true)} onEdit={(row) => setSelected(row as Supplier)} onDeactivate={(row) => setConfirm(row as Supplier)} />
    {(creating || selected) && <SupplierForm supplier={selected} pending={mutations.createSupplier.isPending || mutations.updateSupplier.isPending} error={mutations.createSupplier.error || mutations.updateSupplier.error} onClose={() => { setCreating(false); setSelected(null) }} onSubmit={async (payload) => { if (selected) await mutations.updateSupplier.mutateAsync({ id: selected.id, payload }); else { const created = await mutations.createSupplier.mutateAsync(payload); navigate(`/suppliers/${created.id}`) } setCreating(false); setSelected(null) }} />}
    <ConfirmationDialog open={Boolean(confirm)} title="Deactivate supplier" message={confirm ? deactivationMessage('supplier', confirm.name) : ''} pending={mutations.deactivateSupplier.isPending} onCancel={() => setConfirm(null)} onConfirm={() => { if (confirm) void mutations.deactivateSupplier.mutateAsync(confirm.id).then(() => setConfirm(null)) }} />
  </div>
}

function MasterPage({ title, description, rows, loading, error, filters, setFilter, pages, entity, manage, onCreate, onEdit, onDeactivate }: { title: string; description: string; rows: MasterEntity[]; loading: boolean; error: unknown; filters: Record<string, string>; setFilter: (key: string, value: string) => void; pages: number; entity: 'customer' | 'supplier'; manage: boolean; onCreate: () => void; onEdit: (row: MasterEntity) => void; onDeactivate: (row: MasterEntity) => void }) {
  return <div><Header title={title} description={description} action={manage ? <button onClick={onCreate}>Create {entity}</button> : undefined} /><div className="admin-toolbar partner-toolbar"><input aria-label={`Search ${title.toLowerCase()}`} placeholder="Search by code or name" value={filters.search} onChange={(event) => setFilter('search', event.target.value)} /><select aria-label="Filter by active status" value={filters.active} onChange={(event) => setFilter('active', event.target.value)}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></div>{loading ? <Loading /> : error ? <ErrorState title={`Unable to load ${title.toLowerCase()}`} error={error} /> : !rows.length ? <EmptyState title={`No ${title.toLowerCase()} found`}>Adjust the filters or create a new record.</EmptyState> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Code and name</th><th>Contact</th><th>{entity === 'customer' ? 'Credit limit' : 'Payment terms'}</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link to={`/${entity}s/${row.id}`}><strong>{row.code} · {row.name}</strong></Link></td><td>{row.contact || row.email || '—'}</td><td>{entity === 'customer' ? formatMoney((row as Customer).credit_limit) : `${(row as Supplier).payment_terms_days} days`}</td><td><StatusBadge active={row.is_active} /></td><td>{manage ? <div className="table-actions"><button className="table-button" onClick={() => onEdit(row)}>Edit</button>{row.is_active && <button className="table-button" onClick={() => onDeactivate(row)}>Deactivate</button>}</div> : <span className="muted-label">Read only</span>}</td></tr>)}</tbody></table></div>}<Pagination page={Number(filters.page)} pages={pages} onPage={(page) => setFilter('page', String(page))} /></div>
}

export function CustomerDetailPage() {
  const auth = useAuth(); const { id = '' } = useParams(); const [params, setParams] = useSearchParams(); const query = useCustomer(id); const [editing, setEditing] = useState(false); const [confirm, setConfirm] = useState(false); const mutations = usePartnerMutations(); const tab = params.get('tab') || 'overview'; const customer = query.data; const manage = canManageMasterData(auth.user?.role)
  if (query.isPending) return <Loading />; if (!customer || query.isError) return <ErrorState title="Unable to load customer" error={query.error} />
  return <div className="admin-page partner-page"><Link className="back-link" to="/customers">← Back to customers</Link><Header title={customer.name} description={`${customer.code} · Customer account`} action={manage ? <button onClick={() => setEditing(true)}>Edit customer</button> : undefined} /><Tabs active={tab} onSelect={(value) => { const next = new URLSearchParams(params); next.set('tab', value); setParams(next) }} statement />{tab === 'overview' ? <EntityDetail entity={customer} extra={<><div><dt>Credit limit</dt><dd>{formatMoney(customer.credit_limit)}</dd></div>{manage && customer.is_active && <button className="danger-button" onClick={() => setConfirm(true)}>Deactivate customer</button>}</>} /> : <Statement customerId={id} params={params} setParams={setParams} />}{editing && <CustomerForm customer={customer} pending={mutations.updateCustomer.isPending} error={mutations.updateCustomer.error} onClose={() => setEditing(false)} onSubmit={async (payload) => { await mutations.updateCustomer.mutateAsync({ id, payload }); setEditing(false) }} />}<ConfirmationDialog open={confirm} title="Deactivate customer" message={deactivationMessage('customer', customer.name)} pending={mutations.deactivateCustomer.isPending} onCancel={() => setConfirm(false)} onConfirm={() => void mutations.deactivateCustomer.mutateAsync(id).then(() => setConfirm(false))} /></div>
}

export function SupplierDetailPage() {
  const auth = useAuth(); const { id = '' } = useParams(); const query = useSupplier(id); const [editing, setEditing] = useState(false); const [confirm, setConfirm] = useState(false); const mutations = usePartnerMutations(); const supplier = query.data; const manage = canManageMasterData(auth.user?.role)
  if (query.isPending) return <Loading />; if (!supplier || query.isError) return <ErrorState title="Unable to load supplier" error={query.error} />
  return <div className="admin-page partner-page"><Link className="back-link" to="/suppliers">← Back to suppliers</Link><Header title={supplier.name} description={`${supplier.code} · Supplier account`} action={manage ? <button onClick={() => setEditing(true)}>Edit supplier</button> : undefined} /><EntityDetail entity={supplier} extra={<><div><dt>Payment terms</dt><dd>{supplier.payment_terms_days} days</dd></div>{manage && supplier.is_active && <button className="danger-button" onClick={() => setConfirm(true)}>Deactivate supplier</button>}</>} />{editing && <SupplierForm supplier={supplier} pending={mutations.updateSupplier.isPending} error={mutations.updateSupplier.error} onClose={() => setEditing(false)} onSubmit={async (payload) => { await mutations.updateSupplier.mutateAsync({ id, payload }); setEditing(false) }} />}<ConfirmationDialog open={confirm} title="Deactivate supplier" message={deactivationMessage('supplier', supplier.name)} pending={mutations.deactivateSupplier.isPending} onCancel={() => setConfirm(false)} onConfirm={() => void mutations.deactivateSupplier.mutateAsync(id).then(() => setConfirm(false))} /></div>
}

function Statement({ customerId, params, setParams }: { customerId: string; params: URLSearchParams; setParams: SearchSetter }) { const filters = { from: params.get('from') || '', to: params.get('to') || '', branch_id: params.get('branch_id') || '' }; const query = useCustomerStatement(customerId, filters); const set = (key: string, value: string) => setUrl(params, setParams, key, value); if (query.isPending) return <Loading />; if (!query.data || query.isError) return <ErrorState title="Unable to load statement" error={query.error} />; const data = query.data; const reconciled = statementReconciles(data.opening_balance, data.entries, data.closing_balance); return <section className="statement-panel"><div className="movement-filters"><input aria-label="Statement from date" type="date" value={filters.from} onChange={(event) => set('from', event.target.value)} /><input aria-label="Statement to date" type="date" value={filters.to} onChange={(event) => set('to', event.target.value)} /><input aria-label="Statement branch ID" placeholder="Branch ID" value={filters.branch_id} onChange={(event) => set('branch_id', event.target.value)} /></div><div className="statement-summary"><article><span>Opening balance</span><strong>{formatMoney(data.opening_balance)}</strong></article><article><span>Closing balance</span><strong>{formatMoney(data.closing_balance)}</strong></article><article className={reconciled ? 'reconciled' : 'not-reconciled'}><span>Reconciliation</span><strong>{reconciled ? '✓ Reconciled' : '! Review totals'}</strong></article></div>{!data.entries.length ? <EmptyState title="No statement entries">The returned opening and closing balances are still shown above.</EmptyState> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Type / reference</th><th>Debit</th><th>Credit</th><th>Running balance</th></tr></thead><tbody>{data.entries.map((entry) => <tr key={entry.id}><td>{entry.date}</td><td>{entry.type}<small className="table-subtitle">{entry.reference}</small></td><td>{formatMoney(entry.debit)}</td><td>{formatMoney(entry.credit)}</td><td><strong>{formatMoney(entry.running_balance)}</strong></td></tr>)}</tbody></table></div>}</section> }

export function ExpenseCategoriesPage() { const auth = useAuth(); const [params, setParams] = useSearchParams(); const query = useExpenseCategories({ search: params.get('search') || '', active: params.get('active') || '', page: params.get('page') || '1', per_page: '20' }); const mutations = usePartnerMutations(); const [editing, setEditing] = useState<ExpenseCategory | null>(null); const [creating, setCreating] = useState(false); const [confirm, setConfirm] = useState<ExpenseCategory | null>(null); const manage = canManageExpenseCategories(auth.user?.role); const rows = query.data?.rows || []; return <div className="admin-page partner-page"><Header title="Expense categories" description="Maintain the controlled categories used when recording expenses." action={manage ? <button onClick={() => setCreating(true)}>Create category</button> : undefined} /><div className="admin-toolbar"><input aria-label="Search expense categories" placeholder="Search by code or name" value={params.get('search') || ''} onChange={(event) => setUrl(params, setParams, 'search', event.target.value)} /></div>{query.isPending ? <Loading /> : query.isError ? <ErrorState title="Unable to load expense categories" error={query.error} /> : !rows.length ? <EmptyState title="No expense categories found">Create the first category or adjust your search.</EmptyState> : <div className="category-grid">{rows.map((row) => <article className="category-card" key={row.id}><div><span>{row.code}</span><strong>{row.name}</strong></div><StatusBadge active={row.is_active} />{manage && <div className="table-actions"><button className="table-button" onClick={() => setEditing(row)}>Edit</button>{row.is_active && <button className="table-button" onClick={() => setConfirm(row)}>Deactivate</button>}</div>}</article>)}</div>}<Pagination page={Number(params.get('page') || '1')} pages={query.data?.meta?.pages || 1} onPage={(page) => setUrl(params, setParams, 'page', String(page))} />{(creating || editing) && <CategoryForm category={editing} pending={mutations.createCategory.isPending || mutations.updateCategory.isPending} error={mutations.createCategory.error || mutations.updateCategory.error} onClose={() => { setCreating(false); setEditing(null) }} onSubmit={async (payload) => { if (editing) await mutations.updateCategory.mutateAsync({ id: editing.id, payload }); else await mutations.createCategory.mutateAsync(payload); setCreating(false); setEditing(null) }} />}<ConfirmationDialog open={Boolean(confirm)} title="Deactivate expense category" message={confirm ? deactivationMessage('expense category', confirm.name) : ''} pending={mutations.deactivateCategory.isPending} onCancel={() => setConfirm(null)} onConfirm={() => { if (confirm) void mutations.deactivateCategory.mutateAsync(confirm.id).then(() => setConfirm(null)) }} /></div> }

function CustomerForm({ customer, pending, error, onClose, onSubmit }: { customer: Customer | null; pending: boolean; error: unknown; onClose: () => void; onSubmit: (payload: CustomerPayload) => Promise<void> }) { const [form, setForm] = useState<CustomerPayload>({ code: customer?.code || '', name: customer?.name || '', contact: customer?.contact || '', email: customer?.email || '', address: customer?.address || '', credit_limit: customer?.credit_limit || '0.00', is_active: customer?.is_active ?? true }); return <EntityForm title={customer ? 'Edit customer' : 'Create customer'} form={form} setForm={setForm} pending={pending} error={error} onClose={onClose} onSubmit={onSubmit} extra={<Field label="Credit limit" value={form.credit_limit} onChange={(value) => setForm({ ...form, credit_limit: value })} error={fieldError(error, 'credit_limit')} required inputMode="decimal" />} /> }
function SupplierForm({ supplier, pending, error, onClose, onSubmit }: { supplier: Supplier | null; pending: boolean; error: unknown; onClose: () => void; onSubmit: (payload: SupplierPayload) => Promise<void> }) { const [form, setForm] = useState<SupplierPayload>({ code: supplier?.code || '', name: supplier?.name || '', contact: supplier?.contact || '', email: supplier?.email || '', address: supplier?.address || '', payment_terms_days: supplier?.payment_terms_days || 0, is_active: supplier?.is_active ?? true }); return <EntityForm title={supplier ? 'Edit supplier' : 'Create supplier'} form={form} setForm={setForm} pending={pending} error={error} onClose={onClose} onSubmit={onSubmit} extra={<Field label="Payment terms (days)" type="number" value={String(form.payment_terms_days)} onChange={(value) => setForm({ ...form, payment_terms_days: Number(value) })} error={fieldError(error, 'payment_terms_days')} required />} /> }
function EntityForm<T extends CustomerPayload | SupplierPayload>({ title, form, setForm, pending, error, onClose, onSubmit, extra }: { title: string; form: T; setForm: (value: T) => void; pending: boolean; error: unknown; onClose: () => void; onSubmit: (value: T) => Promise<void>; extra: ReactNode }) { return <Modal title={title} onClose={onClose}><form className="admin-form" onSubmit={(event) => { event.preventDefault(); void onSubmit(form) }}><Field label="Code" value={form.code} onChange={(value) => setForm({ ...form, code: value })} error={fieldError(error, 'code')} required /><Field label="Name" value={form.name} onChange={(value) => setForm({ ...form, name: value })} error={fieldError(error, 'name')} required /><Field label="Contact" value={form.contact || ''} onChange={(value) => setForm({ ...form, contact: value })} error={fieldError(error, 'contact')} /><Field label="Email" type="email" value={form.email || ''} onChange={(value) => setForm({ ...form, email: value })} error={fieldError(error, 'email')} /><Field label="Address" value={form.address || ''} onChange={(value) => setForm({ ...form, address: value })} error={fieldError(error, 'address')} />{extra}<FormActions pending={pending} onClose={onClose} error={error} /></form></Modal> }
function CategoryForm({ category, pending, error, onClose, onSubmit }: { category: ExpenseCategory | null; pending: boolean; error: unknown; onClose: () => void; onSubmit: (payload: ExpenseCategoryPayload) => Promise<void> }) { const [form, setForm] = useState<ExpenseCategoryPayload>({ code: category?.code || '', name: category?.name || '', is_active: category?.is_active ?? true }); return <Modal title={category ? 'Edit expense category' : 'Create expense category'} onClose={onClose}><form className="admin-form" onSubmit={(event: FormEvent) => { event.preventDefault(); void onSubmit(form) }}><Field label="Code" value={form.code} onChange={(code) => setForm({ ...form, code })} error={fieldError(error, 'code')} required /><Field label="Name" value={form.name} onChange={(name) => setForm({ ...form, name })} error={fieldError(error, 'name')} required /><FormActions pending={pending} onClose={onClose} error={error} /></form></Modal> }
function EntityDetail({ entity, extra }: { entity: MasterEntity; extra: ReactNode }) { return <section className="entity-detail"><div className="entity-avatar">{entity.code.slice(0, 2)}</div><dl><div><dt>Status</dt><dd><StatusBadge active={entity.is_active} /></dd></div><div><dt>Contact</dt><dd>{entity.contact || '—'}</dd></div><div><dt>Email</dt><dd>{entity.email || '—'}</dd></div><div><dt>Address</dt><dd>{entity.address || '—'}</dd></div>{extra}</dl></section> }
function Tabs({ active, onSelect, statement }: { active: string; onSelect: (value: string) => void; statement: boolean }) { return <div className="detail-tabs" role="tablist"><button className={active === 'overview' ? 'active' : ''} onClick={() => onSelect('overview')}>Overview</button>{statement && <button className={active === 'statement' ? 'active' : ''} onClick={() => onSelect('statement')}>Statement</button>}</div> }
function Header({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="page-heading admin-header"><div><span className="section-kicker">Relationships</span><h1>{title}</h1><p>{description}</p></div>{action}</div> }
function Field({ label, value, onChange, type = 'text', error, required, inputMode }: { label: string; value: string; onChange: (value: string) => void; type?: string; error?: string; required?: boolean; inputMode?: 'decimal' }) { return <label>{label}<input type={type} inputMode={inputMode} value={value} onChange={(event) => onChange(event.target.value)} required={required} /><small className="field-error">{error || ''}</small></label> }
function FormActions({ pending, onClose, error }: { pending: boolean; onClose: () => void; error: unknown }) { return <><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button disabled={pending}>{pending ? 'Saving...' : 'Save'}</button></div>{Boolean(error) && <div className="form-message error" role="alert">{message(error)}</div>}</> }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="partner-modal-title"><div className="modal-heading"><h2 id="partner-modal-title">{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}>×</button></div>{children}</section></div> }
function Loading() { return <div className="loading-block" role="status">Loading records...</div> }
function ErrorState({ title, error }: { title: string; error: unknown }) { return <div className="inline-error" role="alert"><strong>{title}</strong><span>{message(error)}</span></div> }
