import { useState, type FormEvent, type ReactNode } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { useAuth } from '../../auth/authContext'
import { EmptyState, Pagination } from '../../components/AdminUI'
import { downloadBlob } from '../../lib/download'
import { formatMoney } from '../../lib/money'
import { useBranches } from '../admin/adminApi'
import { useInvoice, useInvoices } from '../invoices/invoiceApi'
import { useCustomers } from '../partners/partnerApi'
import { getReceiptPdf, useAgingAnalysis, useOutstandingReceivables, usePayment, usePaymentMutations, usePayments } from './paymentApi'
import { amountError, canPayInvoice, canReversePayment, isOverpaymentError, paymentScope } from './paymentUtils'
import type { Payment } from './types'

function message(error: unknown) { return error instanceof Error ? error.message : 'The request could not be completed.' }
function Header({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <><div className="page-heading payment-header"><div><span className="section-kicker">Accounts receivable</span><h1>{title}</h1><p>{description}</p></div>{action}</div><nav className="payment-tabs"><Link to="/payments">Payments</Link><Link to="/receivables/outstanding">Outstanding</Link><Link to="/receivables/aging">Aging analysis</Link></nav></> }
function Loading() { return <div className="loading-block" role="status">Loading financial records...</div> }
function ErrorState({ error }: { error: unknown }) { return <div className="inline-error" role="alert"><strong>Unable to complete request</strong><span>{message(error)}</span></div> }
function updateUrl(setParams: (value: URLSearchParams | ((current: URLSearchParams) => URLSearchParams)) => void, key: string, value: string) { setParams((current) => { const next = new URLSearchParams(current); if (value) next.set(key, value); else next.delete(key); if (key !== 'page') next.set('page', '1'); return next }) }
function Status({ payment }: { payment: Payment }) { return <span className={`payment-status ${payment.is_reversed ? 'reversed' : 'posted'}`}><span aria-hidden="true">{payment.is_reversed ? '↶' : '✓'}</span>{payment.is_reversed ? 'Reversed' : 'Posted'}</span> }
function useScope() { const auth = useAuth(); const [params, setParams] = useSearchParams(); return { auth, params, setParams, scope: paymentScope(auth.user!.role, auth.user!.branch_id, params.get('branch_id') || '') } }
function BranchField({ value, locked, onChange }: { value: string; locked: boolean; onChange: (value: string) => void }) { const query = useBranches({ active: 'true', per_page: '100' }); const row = query.data?.rows.find((branch) => branch.id === value); return <label>Branch{locked ? <input aria-label="Assigned payment branch" value={row ? `${row.code} · ${row.name}` : value} readOnly /> : <select aria-label="Payment branch" value={value} onChange={(e) => onChange(e.target.value)}><option value="">All branches</option>{query.data?.rows.map((branch) => <option key={branch.id} value={branch.id}>{branch.code} · {branch.name}</option>)}</select>}</label> }

export function PaymentsPage() {
  const { params, setParams, scope } = useScope(); const filters = { branch_id: scope.branchId, invoice_id: params.get('invoice_id') || '', customer_id: params.get('customer_id') || '', method: params.get('method') || '', reversed: params.get('reversed') || '', from: params.get('from') || '', to: params.get('to') || '', page: params.get('page') || '1', per_page: '20' }; const query = usePayments(filters); const customers = useCustomers({ active: 'true', per_page: '100' }); const set = (key: string, value: string) => updateUrl(setParams, key, value); const rows = query.data?.rows || []
  return <div className="payment-page"><Header title="Payments" description="Record, inspect, reverse, and print customer payments." action={<Link className="primary-link" to="/payments/new">Record payment</Link>} /><div className="payment-toolbar"><BranchField value={scope.branchId} locked={scope.locked} onChange={(v) => set('branch_id', v)} /><input aria-label="Filter payment invoice ID" placeholder="Invoice ID" value={filters.invoice_id} onChange={(e) => set('invoice_id', e.target.value)} /><label>Customer<select aria-label="Filter payment customer" value={filters.customer_id} onChange={(e) => set('customer_id', e.target.value)}><option value="">All customers</option>{customers.data?.rows.map((row) => <option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</select></label><label>Method<select aria-label="Filter payment method" value={filters.method} onChange={(e) => set('method', e.target.value)}><option value="">All methods</option><option>CASH</option><option>CARD</option><option>BANK_TRANSFER</option><option>CHEQUE</option></select></label><label>Status<select aria-label="Filter reversal status" value={filters.reversed} onChange={(e) => set('reversed', e.target.value)}><option value="">All statuses</option><option value="false">Posted</option><option value="true">Reversed</option></select></label><input aria-label="Payments from" type="date" value={filters.from} onChange={(e) => set('from', e.target.value)} /><input aria-label="Payments to" type="date" value={filters.to} onChange={(e) => set('to', e.target.value)} /></div>{query.isPending ? <Loading /> : query.isError ? <ErrorState error={query.error} /> : !rows.length ? <EmptyState title="No payments found">Record a payment or adjust the filters.</EmptyState> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Payment</th><th>Invoice</th><th>Customer</th><th>Date</th><th>Method</th><th>Amount</th><th>Status</th></tr></thead><tbody>{rows.map((payment) => <tr className={payment.is_reversed ? 'reversed-row' : ''} key={payment.id}><td><Link to={`/payments/${payment.id}`}>{payment.id}</Link></td><td>{payment.invoice_no}</td><td>{payment.customer_code}<small>{payment.customer_name}</small></td><td>{payment.payment_date}</td><td>{payment.method}</td><td>{formatMoney(payment.amount)}</td><td><Status payment={payment} /></td></tr>)}</tbody></table></div>}<Pagination page={Number(filters.page)} pages={query.data?.meta?.pages || 1} onPage={(page) => set('page', String(page))} /></div>
}

export function RecordPaymentPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const auth = useAuth(); const [invoiceId, setInvoiceId] = useState(params.get('invoice_id') || ''); const scope = paymentScope(auth.user!.role, auth.user!.branch_id, ''); const invoices = useInvoices({ branch_id: scope.branchId, per_page: '100' }); const invoiceQuery = useInvoice(invoiceId, scope.branchId || undefined); const invoice = invoiceQuery.data; const eligible = (invoices.data?.rows || []).filter(canPayInvoice); const mutations = usePaymentMutations(); const [date, setDate] = useState(''); const [amount, setAmount] = useState(''); const [method, setMethod] = useState('CASH'); const [reference, setReference] = useState(''); const validation = invoice ? amountError(amount, invoice.balance_due) : undefined; const submit = async (event: FormEvent) => { event.preventDefault(); if (!invoice || !canPayInvoice(invoice) || validation) return; const result = await mutations.create.mutateAsync({ invoice_id: invoice.id, payment_date: date || undefined, amount, method, reference: reference || undefined }); navigate(`/payments/${result.payment.id}`) }
  return <div className="payment-page"><Link className="back-link" to="/payments">← Back to payments</Link><Header title="Record payment" description="Start from an eligible issued invoice and wait for the backend result." /><form className="record-payment" onSubmit={submit}><label>Eligible invoice<select aria-label="Payment invoice" value={invoiceId} onChange={(e) => { setInvoiceId(e.target.value); setAmount('') }} required><option value="">Select invoice</option>{eligible.map((row) => <option key={row.id} value={row.id}>{row.invoice_no} · {row.customer_name} · {formatMoney(row.balance_due)}</option>)}</select></label>{invoice && <section className="invoice-balance-card"><span>Current invoice balance</span><strong>{formatMoney(invoice.balance_due)}</strong><small>{invoice.status} · {invoice.customer_name}</small>{!canPayInvoice(invoice) && <div className="form-message error">This invoice is not eligible for payment.</div>}</section>}<label>Payment date<input aria-label="Customer payment date" type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label><label>Amount<input aria-label="Customer payment amount" inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} required /><small className="field-error">{amount ? validation : ''}</small></label><label>Method<select aria-label="Customer payment method" value={method} onChange={(e) => setMethod(e.target.value)}><option>CASH</option><option>CARD</option><option>BANK_TRANSFER</option><option>CHEQUE</option></select></label><label>Reference<input aria-label="Customer payment reference" value={reference} onChange={(e) => setReference(e.target.value)} /></label><button disabled={mutations.create.isPending || !invoice || !canPayInvoice(invoice) || Boolean(validation)}>{mutations.create.isPending ? 'Recording...' : 'Record payment'}</button>{Boolean(mutations.create.error) && <ErrorState error={mutations.create.error} />}{isOverpaymentError(mutations.create.error) && <div className="overpayment-error">! Backend rejected this as an overpayment.</div>}</form></div>
}

export function PaymentDetailPage() {
  const { id = '' } = useParams(); const auth = useAuth(); const query = usePayment(id, auth.user?.branch_id || undefined); const mutations = usePaymentMutations(); const [reverseOpen, setReverseOpen] = useState(false); const [pdf, setPdf] = useState<string | null>(null); const [pdfError, setPdfError] = useState<unknown>(null); const payment = query.data; if (query.isPending) return <Loading />; if (!payment || query.isError) return <ErrorState error={query.error} />; const load = async (download: boolean) => { try { const file = await getReceiptPdf(id); if (download) downloadBlob(file.blob, file.filename); else { if (pdf) URL.revokeObjectURL(pdf); setPdf(URL.createObjectURL(file.blob)) } } catch (error) { setPdfError(error) } }
  return <div className="payment-page"><Link className="back-link" to="/payments">← Back to payments</Link><Header title={`Payment ${payment.id}`} description={`${payment.invoice_no} · ${payment.customer_name}`} action={<div className="header-actions">{canReversePayment(payment) && <button className="danger-button" onClick={() => setReverseOpen(true)}>Reverse payment</button>}<button className="secondary-button" onClick={() => void load(false)}>Preview receipt</button><button className="secondary-button" onClick={() => void load(true)}>Download receipt</button></div>} /><section className="payment-detail"><div><span>Status</span><Status payment={payment} /></div><div><span>Amount</span><strong>{formatMoney(payment.amount)}</strong></div><div><span>Date</span><strong>{payment.payment_date}</strong></div><div><span>Method</span><strong>{payment.method}</strong></div><div><span>Reference</span><strong>{payment.reference || '—'}</strong></div><div><span>Branch</span><strong>{payment.branch_code}</strong></div></section>{payment.is_reversed && <section className="reversal-result"><strong>↶ Payment reversed</strong><span>{payment.reversal_reason}</span></section>}{Boolean(pdfError) && <ErrorState error={pdfError} />}{pdf && <section className="pdf-preview"><header><strong>Receipt PDF preview</strong><button className="secondary-button" onClick={() => { URL.revokeObjectURL(pdf); setPdf(null) }}>Close preview</button></header><iframe title={`Receipt preview ${payment.id}`} src={pdf} /></section>}{reverseOpen && <ReverseDialog payment={payment} pending={mutations.reverse.isPending} error={mutations.reverse.error} onClose={() => setReverseOpen(false)} onSubmit={(reason) => void mutations.reverse.mutateAsync({ id, reason }).then(() => setReverseOpen(false))} />}</div>
}

function ReverseDialog({ payment, pending, error, onClose, onSubmit }: { payment: Payment; pending: boolean; error: unknown; onClose: () => void; onSubmit: (reason: string) => void }) { const [reason, setReason] = useState(''); return <Modal title="Reverse payment" onClose={onClose}><form className="reverse-form" onSubmit={(e) => { e.preventDefault(); onSubmit(reason) }}><p>Reversing {formatMoney(payment.amount)} restores the invoice balance using the backend response. This cannot be hidden from payment history.</p><label>Reversal reason<textarea aria-label="Payment reversal reason" value={reason} onChange={(e) => setReason(e.target.value)} required /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Keep payment</button><button className="danger-button" disabled={pending || !reason.trim()}>{pending ? 'Reversing...' : 'Reverse payment'}</button></div>{Boolean(error) && <ErrorState error={error} />}</form></Modal> }

export function OutstandingReceivablesPage() { const { params, setParams, scope } = useScope(); const filters = { branch_id: scope.branchId, customer_id: params.get('customer_id') || '', as_of: params.get('as_of') || '' }; const query = useOutstandingReceivables(filters); const customers = useCustomers({ active: 'true', per_page: '100' }); const set = (key: string, value: string) => updateUrl(setParams, key, value); const data = query.data; const rows = Array.isArray(data?.rows) ? data.rows : []; return <div className="payment-page"><Header title="Outstanding receivables" description="Invoice balances and overdue days exactly as returned by the backend." /><div className="receivable-toolbar"><BranchField value={scope.branchId} locked={scope.locked} onChange={(v) => set('branch_id', v)} /><label>Customer<select aria-label="Receivables customer" value={filters.customer_id} onChange={(e) => set('customer_id', e.target.value)}><option value="">All customers</option>{customers.data?.rows.map((row) => <option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</select></label><label>As of<input aria-label="Receivables as of date" type="date" value={filters.as_of} onChange={(e) => set('as_of', e.target.value)} /></label></div>{query.isPending ? <Loading /> : query.isError ? <ErrorState error={query.error} /> : data && <><section className="receivable-total"><span>Total outstanding as of {data.as_of}</span><strong>{formatMoney(data.total_outstanding)}</strong></section>{!rows.length ? <EmptyState title="No outstanding receivables">No unpaid balances were returned.</EmptyState> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Invoice</th><th>Customer</th><th>Branch</th><th>Invoice / due date</th><th>Days overdue</th><th>Net amount</th><th>Paid</th><th>Balance due</th><th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.invoice_id}><td>{row.invoice_no}</td><td>{row.customer_code}<small>{row.customer_name}</small></td><td>{row.branch_code}</td><td>{row.invoice_date}<small>{row.due_date || 'No due date'}</small></td><td>{row.days_overdue}</td><td>{formatMoney(row.net_amount)}</td><td>{formatMoney(row.amount_paid)}</td><td><strong>{formatMoney(row.balance_due)}</strong></td><td><Link to={`/payments/new?invoice_id=${row.invoice_id}`}>Record payment</Link></td></tr>)}</tbody></table></div>}</>}</div> }
export function AgingPage() { const { params, setParams, scope } = useScope(); const filters = { branch_id: scope.branchId, as_of: params.get('as_of') || '' }; const query = useAgingAnalysis(filters); const set = (key: string, value: string) => updateUrl(setParams, key, value); const data = query.data; return <div className="payment-page"><Header title="Receivables aging" description="Backend-defined aging buckets and totals without frontend recomputation." /><div className="receivable-toolbar aging"><BranchField value={scope.branchId} locked={scope.locked} onChange={(v) => set('branch_id', v)} /><label>As of<input aria-label="Aging as of date" type="date" value={filters.as_of} onChange={(e) => set('as_of', e.target.value)} /></label></div>{query.isPending ? <Loading /> : query.isError ? <ErrorState error={query.error} /> : data && <><section className="receivable-total"><span>Total outstanding as of {data.as_of}</span><strong>{formatMoney(data.total_outstanding)}</strong></section><div className="aging-grid">{data.buckets.map((bucket) => <article key={bucket.name}><span>{bucket.name}</span><strong>{formatMoney(bucket.amount)}</strong><small>{bucket.invoice_count} invoice(s) · {bucket.from_days ?? 'Any'}–{bucket.to_days ?? '∞'} days</small></article>)}</div></>}</div> }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="payment-modal-title"><div className="modal-heading"><h2 id="payment-modal-title">{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}>×</button></div>{children}</section></div> }