import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, request } from '../../api/client'
import { getFilenameFromDisposition } from '../../lib/download'
import type { Invoice } from '../invoices/types'
import { buildPaymentParams } from './paymentUtils'
import type { AgingAnalysis, BinaryFile, OutstandingReceivables, Pagination, Payment, PaymentFilters, PaymentPayload, PaymentResult } from './types'

export const paymentKeys = { all: () => ['payments'] as const, list: (filters: PaymentFilters) => ['payments', 'list', filters] as const, detail: (id: string) => ['payments', 'detail', id] as const, receivables: () => ['receivables'] as const, outstanding: (filters: Record<string, string>) => ['receivables', 'outstanding', filters] as const, aging: (filters: Record<string, string>) => ['receivables', 'aging', filters] as const }
export function usePayments(filters: PaymentFilters) { return useQuery({ queryKey: paymentKeys.list(filters), queryFn: async () => { const result = await request<Payment[]>({ method: 'GET', url: '/payments', params: buildPaymentParams(filters) }); return { rows: result.data, meta: result.meta as Pagination | undefined } } }) }
export function usePayment(id: string, branchId?: string) { return useQuery({ queryKey: paymentKeys.detail(id), queryFn: async () => (await request<Payment>({ method: 'GET', url: `/payments/${id}`, params: branchId ? { branch_id: branchId } : undefined })).data, enabled: Boolean(id) }) }
export function useOutstandingReceivables(filters: { branch_id?: string; customer_id?: string; as_of?: string }) { return useQuery({ queryKey: paymentKeys.outstanding(filters as Record<string, string>), queryFn: async () => (await request<OutstandingReceivables>({ method: 'GET', url: '/receivables/outstanding', params: Object.fromEntries(Object.entries(filters).filter(([, value]) => value)) })).data }) }
export function useAgingAnalysis(filters: { branch_id?: string; as_of?: string }) { return useQuery({ queryKey: paymentKeys.aging(filters as Record<string, string>), queryFn: async () => (await request<AgingAnalysis>({ method: 'GET', url: '/receivables/aging', params: Object.fromEntries(Object.entries(filters).filter(([, value]) => value)) })).data }) }
export function usePaymentMutations() { const client = useQueryClient(); const refresh = (invoice: Invoice, payment: Payment) => { client.setQueryData(paymentKeys.detail(payment.id), payment); client.setQueryData(['invoices', 'detail', invoice.id], invoice); void client.invalidateQueries({ queryKey: paymentKeys.all() }); void client.invalidateQueries({ queryKey: ['invoices'] }); void client.invalidateQueries({ queryKey: paymentKeys.receivables() }); void client.invalidateQueries({ queryKey: ['customers', 'statement', invoice.customer_id] }); void client.invalidateQueries({ queryKey: ['reports', 'dashboard'] }) }; const create = useMutation({ mutationFn: (payload: PaymentPayload) => request<PaymentResult>({ method: 'POST', url: '/payments', data: payload }).then((r) => r.data), onSuccess: (result) => refresh(result.invoice, result.payment) }); const reverse = useMutation({ mutationFn: ({ id, reason }: { id: string; reason: string }) => request<PaymentResult>({ method: 'POST', url: `/payments/${id}/reverse`, data: { reason } }).then((r) => r.data), onSuccess: (result) => refresh(result.invoice, result.payment) }); return { create, reverse } }
export async function getReceiptPdf(id: string): Promise<BinaryFile> { const response = await api.get<Blob>(`/payments/${id}/receipt-pdf`, { responseType: 'blob' }); return { blob: response.data, filename: getFilenameFromDisposition(response.headers['content-disposition']) || `receipt-${id}.pdf` } }
