import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { request } from '../../api/client'
import { buildTransferParams } from './transferUtils'
import type { CancelResult, DispatchResult, InTransit, Pagination, ReceiveResult, Transfer, TransferFilters, TransferPayload } from './types'

export const transferKeys = { all: () => ['transfers'] as const, list: (filters: TransferFilters) => ['transfers', 'list', filters] as const, detail: (id: string, branchId = '') => ['transfers', 'detail', id, branchId] as const, detailPrefix: (id: string) => ['transfers', 'detail', id] as const, inTransit: (filters: { branch_id?: string; product_id?: string }) => ['transfers', 'in-transit', filters] as const }
export function useTransfers(filters: TransferFilters) { return useQuery({ queryKey: transferKeys.list(filters), queryFn: async () => { const result = await request<Transfer[]>({ method: 'GET', url: '/transfers', params: buildTransferParams(filters) }); return { rows: result.data, meta: result.meta as Pagination | undefined } } }) }
export function useTransfer(id: string, branchId?: string) { return useQuery({ queryKey: transferKeys.detail(id, branchId), queryFn: async () => (await request<Transfer>({ method: 'GET', url: `/transfers/${id}`, params: branchId ? { branch_id: branchId } : undefined })).data, enabled: Boolean(id) }) }
export function useInTransit(filters: { branch_id?: string; product_id?: string }) { return useQuery({ queryKey: transferKeys.inTransit(filters), queryFn: async () => (await request<InTransit>({ method: 'GET', url: '/transfers/in-transit', params: Object.fromEntries(Object.entries(filters).filter(([, value]) => value)) })).data }) }
export function useTransferMutations() { const client = useQueryClient(); const refresh = (transfer: Transfer) => { client.setQueriesData({ queryKey: transferKeys.detailPrefix(String(transfer.id)) }, transfer); void client.invalidateQueries({ queryKey: transferKeys.all() }) }; const stock = () => { void client.invalidateQueries({ queryKey: ['stock'] }); void client.invalidateQueries({ queryKey: ['products', 'movement'] }); void client.invalidateQueries({ queryKey: ['reports'] }) }; const create = useMutation({ mutationFn: (payload: TransferPayload) => request<Transfer>({ method: 'POST', url: '/transfers', data: payload }).then((r) => r.data), onSuccess: refresh }); const dispatch = useMutation({ mutationFn: ({ id, dispatch_date }: { id: string; dispatch_date?: string }) => request<DispatchResult>({ method: 'POST', url: `/transfers/${id}/dispatch`, data: { dispatch_date: dispatch_date || undefined } }).then((r) => r.data), onSuccess: (result) => { refresh(result.transfer); stock() } }); const receive = useMutation({ mutationFn: ({ id, receive_date, lines }: { id: string; receive_date?: string; lines: Array<{ line_id: number; received_qty: number }> }) => request<ReceiveResult>({ method: 'POST', url: `/transfers/${id}/receive`, data: { receive_date: receive_date || undefined, lines } }).then((r) => r.data), onSuccess: (result) => { refresh(result.transfer); stock() } }); const cancel = useMutation({ mutationFn: ({ id, reason }: { id: string; reason: string }) => request<CancelResult>({ method: 'POST', url: `/transfers/${id}/cancel`, data: { reason } }).then((r) => r.data), onSuccess: (result) => { refresh(result.transfer); stock() } }); return { create, dispatch, receive, cancel } }
